name: student_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  win32: ^5.5.3
  path_provider: ^2.1.1
  image_picker: ^0.8.3+3
  path: ^1.8.3
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.4.12




flutter:


  uses-material-design: true


  assets:
    - assets/student11.jpg
    - assets/3369473.jpg
    - assets/585e4bf3cb11b227491c339a.png
